name: Propose your meme
description: Make a proposal for publication
labels:
  - proposal
assignees:
  - devpolo
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to make a proposal!\n"
  - type: checkboxes
    attributes:
      label: Preflight checklist
      options:
        - label: "I agree to follow this project's [Code of
            Conduct](https://github.com/devpolo/community/blob/main/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have read and am following this repository's [Contribution
            Guidelines](https://github.com/devpolo/community/blob/main/CONTRIBUTING.md)."
          required: true
  - type: textarea
    attributes:
      label: Your proposal
      description: Describe your proposal
      placeholder: |
        Header? Description? Explanation? Anything that will give us more context about your proposal!

        You can attach images, videos or GIFs by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: input
    attributes:
      label: Source / Credit / Author
      description: Please, credit the proposal your are sharing. It can be you or someone else.
      placeholder: vvv.my-source.com/this-proposal | @myself
    validations:
      required: true
  - type: input
    attributes:
      label: Link to your LinkedIn profile
      description: your proposal is likely to be posted on LinkedIn. I would love to thank you by tagging you.
      placeholder: https://www.linkedin.com/in/pcrussaire/
    validations:
      required: false
